(in-package :mgl-mat)

;;;; Generating own docs

(defun update-readmes ()
  (with-open-file (stream (asdf:system-relative-pathname :mgl-mat "README.md")
                          :direction :output
                          :if-does-not-exist :create
                          :if-exists :supersede)
    (document (list @mat-manual @cube-manual) :stream stream)
    (print-markdown-footer stream))
  (with-open-file (stream (asdf:system-relative-pathname :mgl-mat "README")
                          :direction :output
                          :if-does-not-exist :create
                          :if-exists :supersede)
    (describe @mat-manual stream)
    (describe @cube-manual stream)
    (print-markdown-footer stream)))

(defun print-markdown-footer (stream)
  (format stream "~%* * *~%")
  (format stream "###### \\[generated by ~
                   [MGL-PAX](https://github.com/melisgl/mgl-pax)\\]~%"))

#|

(update-readmes)

|#
